version: 0.2

phases:
  build:
    commands:
      - echo "=== Build phase start ==="
      - mkdir -p package
      # src以下をまるごとコピー
      - cp -r src/* ./package/
      # ZIPを作成
      - cd package
      - zip -r ../function.zip .
      - cd ..
      - echo "=== Build phase  ==="

artifacts:
  files:
    - function.zip
  discard-paths: yes
