version: 0.2

phases:
  build:
    commands:
      - echo "=== Build phase start ==="
      - cd src
      - zip -r ../function.zip .   # output.zip → function.zip に修正
      - cd ..
      - echo "=== Build phase finished ==="

artifacts:
  files:
    - function.zip                # Lambda に渡すのはこのZIP
  discard-paths: yes
