version: 0.2

phases:
  build:
    commands:
      - echo "=== Build phase start ==="
      # src 内のコードをそのまま zip 化
      - cd src
      - zip -r ../function.zip .
      - cd ..
      - echo "=== Build phase finished ==="

artifacts:
  files:
    - function.zip
  discard-paths: yes
