version: 0.2

phases:
  build:
    commands:
      - echo "=== Build phase start ==="
      - cd src
      - zip -r ../output.zip .
      - cd ..
      - echo "=== Build phase finished ==="

artifacts:
  files:
    - output.zip
