version: 0.2

phases:
  build:
    commands:
      - echo "=== Build phase start ==="
      - cd src
      - zip -r ../function.zip .
      - cd ..
      - echo "=== Build phase finished ==="

artifacts:
  files:
    - function.zip   # ← この zip がそのまま S3 に保存される
  discard-paths: yes
