version: 0.2

phases:
  build:
    commands:
      - echo "=== Build phase start ==="
      # src 配下のファイルを zip にまとめる（固定名）
      - zip -j lambda_function.zip src/lambda_function.py
      - echo "=== Build phase finished ==="

artifacts:
  files:
    - lambda_function.zip
  base-directory: .
  discard-paths: yes
