version: 0.2

phases:
  build:
    commands:
      - echo "=== Build phase start ==="
      # src 配下のファイルをまとめて固定名の zip にする
      - zip -j lambda_function.zip src/*.py
      - echo "=== Build phase finished ==="
      
artifacts:
  files:
    - lambda_function.py
  base-directory: .
  discard-paths: yes
