version: 0.2

phases:
  build:
    commands:
      - echo "=== Build phase start ==="
      - cp src/*.py .
      - echo "=== Build phase finish ==="

artifacts:
  files:
    - lambda_function.py
  base-directory: .
  discard-paths: yes
