version: 0.2

phases:
  build:
    commands:
      - echo "=== Build phase start ==="
      # TestLambda_with_Proxy_Integration/src 配下のファイルをコピー
      - cp TestLambda_with_Proxy_Integration/src/lambda_function.py .
      - echo "=== Build phase finished ==="

      # 日付付き & latest 用に zip を作成して S3 にアップロード
      - DATE=$(date +%Y%m%d-%H%M)
      - zip -j lambda_function.zip TestLambda_with_Proxy_Integration/src/lambda_function.py
      - aws s3 cp lambda_function.zip s3://lambda-zip-version/TestLambda_with_Proxy_Integration/releases/$DATE/lambda_function.zip
      - aws s3 cp lambda_function.zip s3://lambda-zip-version/TestLambda_with_Proxy_Integration/releases/latest/lambda_function.zip

artifacts:
  files:
    - lambda_function.py
  base-directory: .
  discard-paths: yes
